/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ehu.isad;

import ehu.isad.Controller.ui.ErroreaKud;
import ehu.isad.Controller.ui.HasieraKud;
import ehu.isad.Controller.ui.HerrialdeaHautatuKud;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;

public class App extends Application {

    private Herrialde herrialdea;

    private Parent erroreaUI;
    private Parent hasieraUI;
    private Parent herrialdeaHautatuUI;

    private Stage stage;

    private ErroreaKud erroreakud;
    private HasieraKud hasieraKud;
    private HerrialdeaHautatuKud herrialdeaHautatuKud;



    @Override
    public void start(Stage primaryStage) throws Exception {
        stage = primaryStage;
        pantailakKargatu();

        stage.setTitle("EUROVISION");
        stage.setScene(new Scene(hasieraUI, 450, 275));
        stage.show();
    }

    private void pantailakKargatu() throws IOException {

        FXMLLoader loaderHasiera = new FXMLLoader(getClass().getResource("/Hasiera.fxml"));
        hasieraUI = (Parent) loaderHasiera.load();
        hasieraKud = loaderHasiera.getController();
        hasieraKud.setMainApp(this);


        FXMLLoader loaderMain = new FXMLLoader(getClass().getResource("/HerrialdeaHautatu.fxml"));
        herrialdeaHautatuUI = (Parent) loaderMain.load();
        herrialdeaHautatuKud = loaderMain.getController();
        herrialdeaHautatuKud.setMainApp(this);

        FXMLLoader loaderError = new FXMLLoader(getClass().getResource("/Errorea.fxml"));
        erroreaUI = (Parent) loaderError.load();
        erroreakud = loaderError.getController();
        erroreakud.setMainApp(this);
    }
    public static void main(String[] args) {
        launch(args);
    }

    public void HerrialdeaHautatuErakutsi() {
        stage.setScene(new Scene(herrialdeaHautatuUI));
        stage.show();
        stage.setTitle("Informazioaren eguneraketa");

    }

    public void erroreaErakutsi() {
        stage.setScene(new Scene(erroreaUI));
        stage.show();
        stage.setTitle("xxxx inguruko informazioa");

    }
}
